@baseUrl = http://localhost:8080
@roomId = 1678583e-96bb-4d62-af21-9d02133282e7

GET {{baseUrl}}/room/{{roomId}}

###
POST {{baseUrl}}/room
Content-Type: application/json
Accept: application/json

{
    "available": true,
    "nameRoom": "Cho thuê + loại hình phòng trọ + diện tích + giá + tên đường/quận",
    "typeRoomName": "Phòng Deluxe",
    "owner": "Trí Dũng",
    "phone": "0343285564",
    "description": "Phòng đẹp mới xây",
    "price": 3300000,
    "deposit": 2500000,
    "roomArea": 15,
    "priceElectric": 3500,
    "priceWater": 35000,
    "maxPerson": 2,
    "rentalStartTime": "2024-03-01",
    "hours": "Tự do",
    "modelId": "03dad3d0-24dc-4831-9c8e-9285a84e4027",
    "roomServices": ["Wifi miễn phí", "Hồ bơi"],
    "roomImages": [
        "https://picsum.photos/1000/700?random=1",
        "https://picsum.photos/1000/700?random=2",
        "https://picsum.photos/1000/700?random=3"
    ],
    "rules": [
        "No Pets",
        "No Smoking",
        "Quiet Hours",
        "Visitor Policy",
        "Cleaning Fee"
    ],
    "address": "Bắc Từ Liên"
}
