@baseUrl = http://localhost:8080
@contentType = application/json
@roomId = 026d509d-eeb5-49ce-a517-c7695f20d14e

POST {{baseUrl}}/roomImage
Content-Type: {{contentType}}
Accept: {{contentType}} 

{
    "roomId": "{{roomId}}",
    "image": "https://picsum.photos/1000/700?random=5"
}
