@baseUrl = http://localhost:8080
@contentType = application/json
@roomId = e7850b23-beba-48d8-8b95-8d76adf2482c

POST {{baseUrl}}/roomImage
Content-Type: {{contentType}}
Accept: {{contentType}} 

{
    "roomId": "{{roomId}}",
    "image": "https://picsum.photos/1000/700?random=5"
}
