
@baseUrl = http://localhost:8080
@roomId = 6372465c-ac06-4e2a-94b9-27307ece788e


GET {{baseUrl}}/searchs/price?startPrice=1255565.31&endPrice=4229298.69

###

GET {{baseUrl}}/searchs/name?name=Hà Giang