@baseUrl = http://localhost:8080
@roomId = 06d5fefb-ea1a-4b6b-b6ac-1b23f39b31fb


GET {{baseUrl}}/searchs/price?startPrice=1255565.31&endPrice=4229298.69

###

GET {{baseUrl}}/searchs/name?name=Tây

###

GET {{baseUrl}}/searchs

# Search danh sách phòng theo địa chỉ bằng Elastic Search
###
GET {{baseUrl}}/searchs/address?address=Bình Định

# Search mở danh sách phòng theo địa chỉ bằng Elastic Search
###
GET {{baseUrl}}/searchs/addressFuzzy?address=Bình Định