@baseUrl = http://localhost:8080
@roomId = 21419639-aed3-43a7-8e13-087705d5c57f


GET {{baseUrl}}/searchs/price?startPrice=1255565.31&endPrice=4229298.69

###

GET {{baseUrl}}/searchs/name?name=Hà Giang

GET {{baseUrl}}/searchs