export const Pkeyw = [
  { name: 'Cho thuê phòng trọ Đống Đa' },
  { name: 'Cho thuê phòng trọ Quận Ba Đình' },
  { name: 'Cho thuê phòng trọ Bắc Từ Liêm' },
  { name: 'Cho thuê phòng trọ Gia Lâm' },
  { name: 'Cho thuê phòng trọ Sơn Trà' },
  { name: 'Cho thuê phòng trọ Hà Đông' },
  { name: 'Cho thuê phòng trọ Thanh Xuân' },
  { name: 'Cho thuê phòng trọ Cầu Giấy' },
  { name: 'Cho thuê phòng trọ Hoài Đức' },
  { name: 'Cho thuê phòng trọ Mê Linh' },
  { name: 'Cho thuê phòng trọ Hai Bà Trưng' },
  { name: 'Cho thuê phòng trọ Thường Tín' },
  { name: 'Cho thuê phòng trọ Long Biên' },
  { name: 'Cho thuê phòng trọ Tây Hồ' },
]
